name: docker push

on:
  push:
    branches: [main]

jobs:
  buildx:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-buildx-action@v2
      with:
        driver-opts: env.BUILDKIT_STEP_LOG_MAX_SIZE=10485760
    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository }}
        cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:latest
        cache-to: type=inline
