name: docker push

on:
  push:
    branches: [main]

jobs:
  buildx:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-buildx-action@v2
      with:
        driver-opts: env.BUILDKIT_STEP_LOG_MAX_SIZE=10485760
    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - id: repo
      run: echo "name=ghcr.io/${{ github.repository }}" | tr '[:upper:]' '[:lower:]' >> $GITHUB_OUTPUT
    - uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ steps.repo.outputs.name }}
        cache-from: type=registry,ref=${{ steps.repo.outputs.name }}:latest
        cache-to: type=inline
